version: "3.7"
services:
  api:
    build:
      context: ./goggles-api
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./goggles-api:/app
    environment:
      PGUSER: ${POSTGRES_USER}
      PGDATABASE: ${POSTGRES_DB}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGHOST: ${POSTGRES_HOST}
      PORT: ${API_PORT}
  gui:
    build:
      context: ./react-goggles
      dockerfile: ./Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - ./react-goggles:/app
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
  postgres_db:
    container_name: postgres_db
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - goggles-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  goggles-data:
    external: true
